### PR TITLE
Add visible Emmet add-on...

### PR DESCRIPTION
**Pull request by Defman21**
...which works with Komodo 9 too.

### CODE REVIEW

**Comment by Naatan** [comment]
This will not work, the key "Emmet" is already in use, Defman's version will be overwritten by the one further down in the file.

Aside from that; have you opened a pull request with the original author? I'd prefer this be merged into his codebase rather than having 2 emmet addons that are basically the same except for some tweaks.

**Comment by Defman21** [comment]
Nope, I can't open a pull request to the author because he doesn't put the source of emmet addon for Komodo on GitHub.

**Comment by Naatan** [comment]
Have you tried contacting him?

**Comment by Defman21** [comment]
Nope. I'll try it.

**Comment by Naatan** [comment]
Ok, please feel free to open another pull-request if he does not respond or refuses to incorporate the changes, but ensure you either remove his entry or use a different name for yours. Also make sure you provide proper attribution to the original author.

Thanks Defman!

**Comment by Defman21** [comment]
I just replaced type of the add-on from jar to unpacked xpi so It always will have proper attribution to the original author. (because I don't change the source)

**Comment by Defman21** [comment]
Okay, I talked a bit with Emmet developer in my native language (Russian, because he's probably from Russia too). He'll create his own repository and send a pull request to this repository :)

**Pull request merged**
