### PR TITLE
renamed less compiler and bootstrap snippets

### PR DESCRIPTION
**Pull request by babobski**
renamed less compiler and changed link. renamed boostrap

### CODE REVIEW

**Comment by Naatan** [comment]
Thanks, can't merge this though as your repo is not up to date.

**Comment by babobski** [comment]
updated my repo...

**Comment by Naatan** [comment]
Perfect, thank you :)

**Comment by babobski** [comment]
thanks. Got 2 questions about the implementation on the website
1. i used the javascript comment in my readme but isn't displayed correct(javascript is showing up in the code), is this not supported?
2. how do i get a .xpi link to be displayed on the komodo website

**Comment by Naatan** [comment]
1. I'll fix that when I get a chance, its an issue on our end.
2. Upload the XPI as a release on your repository, here: https://github.com/babobski/Komodo-LESS-Compiler/releases

**Comment by babobski** [comment]
ah clear, added the xpi as release, thanks

**Pull request merged**
