### PR TITLE
Added Komodo 8 collection

### PR DESCRIPTION
**Pull request by Defman21**

### CODE REVIEW

**Comment by Naatan** [comment]
Thanks for taking the initiative :)

One nitpick - they're not "Komodo 8", they're Komodo 8 and before. Can we call it "Komodo Classic Schemes" ?

**Comment by Defman21** [comment]
As you wish!

**Comment by Defman21** [comment]
Renamed.

**Comment by Naatan** [comment]
Perfect :) Thanks!

**Pull request merged**
